os: linux-ppc64le
dist: xenial
language: java
sudo: required
jdk:
  - openjdk8

before_install:
  - mkdir work
  - cd work
  - sudo apt-get update
  - sudo apt-get install -y build-essential python3 zip unzip lftp
  - python3 bazel-version.py

script:
  - bash build.sh
