os: linux
arch: ppc64le
language: shell

#env:
#  - ver=1.2.0

jobs:
  include:
    - dist: xenial
      env: dist_version=16.04
    - dist: bionic
      env: dist_version=18.04

before_install:
  - sudo apt-get update
  - sudo apt-get install build-essential python zip unzip python3-pip
  - sudo apt install default-jre default-jdk
  - sudo pip3 install requests
  - python3 bazel-version.py $dist_version

script:
  - wget -q https://oplab9.parqtec.unicamp.br/pub/ppc64el/bazel/ubuntu_${dist_version}/bazel_bin_ppc64le_2.0.0
  - sudo mv bazel_bin_ppc64le_2.0.0 /usr/local/bin/bazel
  - sudo chmod +x /usr/local/bin/bazel
  - wget -q https://github.com/bazelbuild/bazel/releases/download/$github_version/bazel-$github_version-dist.zip
  - unzip -q bazel-$github_version-dist.zip -d bazel
  - rm bazel/src/main/java/com/google/devtools/build/lib/syntax/BUILD
  - mv BUILD bazel/src/main/java/com/google/devtools/build/lib/syntax/
  - cd bazel
  - sudo EXTRA_BAZEL_ARGS=--host_javabase=@local_jdk//:jdk ./compile.sh
  - sudo mv output/bazel output/bazel_bin_ppc64le_$github_version
  #- bash build.sh

deploy:
  provider: script  
  script: sudo apt-get install -y lftp; echo "funfa" #bash ftp_upload.sh
  skip_cleanup: true

notifications:
  slack:
    rooms:
      - secure: "FWATQ1L0REWlv2r7OBEgmM0X60qGveibTyvvn8fyQbACl/YJKexH0W+FX55Yf4OGp8Hl07ezGb7qpNEi9pZ3mzIWYf14SqN9skn2nPTZGV0eIs6tGQIos6SHXg6xth9HOQRWOGE1xFWtp7ciwvdy67iWJoO7MBf2W1fTP6++5sDR+0/oMVZH9JPM0ubW6kewOlfu7n1Vxzzh/oAwLiRukVdCaiJ0khFmVdQSoym+JNlG5mVTO0jXC91lrRsDWwLcBF/vORNsY38xZZIbAvxETiYZnN8dZo4N0OHtFb/pX7I2hESgsFb+p6hM5bzqMvxspn+f55KIvyZznjSMSpGS9W5eXTtpS7h7rpGVCkj9ULEiuIcYbqGe41lFFEArqKC4u9galUjOXkPnwzpqtkhbR4vjDJ8foB9/8aKPgW0qJ5Oims6ctRu5iLs16DvH1Qq+z1QqaC51Uts3irhxw18Stj7o3bcpXrLwor1zcYeIk7dXcfxzi0VTd1tTOOWs+2qpc41gnDrEEbnFZ9ug5i0fuAVV5WhNEnDJqiG7KUslNmTxc8lXPSLsfq77nOaUluw2vP33mJnCJ+6NQZKfWPfuxp14RNvZtZMEuw1Drvb8oAvUkkdXW1tGyIRDKF+t/LdDH50o0fYFX34Dg0rYcvTtDdxtjHLgPtVYvnZZJKRlxK4="
    on_success: change
    on_failure: always
