os: linux-ppc64le
sudo: required

env:
  - ver=0.28.0
  - ver=0.28.1
  - ver=0.29.0
  - ver=0.29.1
  - ver=1.0.0

before_install:
  - sudo apt-get update
  - sudo apt-get install build-essential openjdk-8-jdk python zip unzip
  - python3 bazel-version.py

script:
  - bash build.sh

deploy:
  provider: script  
  script: sudo apt-get install -y lftp; bash ftp_upload.sh
  skip_cleanup: true
