matrix:
  include:
    - env: ver=0.25.1
    - env: ver=0.25.2
    - env: ver=0.25.3
    - env: ver=0.26.0
    - env: ver=0.26.1
    - env: ver=0.27.0
    - env: ver=0.27.1
    - env: ver=0.27.2

os: linux-ppc64le
dist: xenial
language: java
sudo: required
jdk:
  - openjdk8

before_install:
  - sudo apt-get update
  - sudo apt-get install -y build-essential python3 zip unzip
  - python3 bazel-version.py

script:
  - bash build.sh

deploy:
  provider: script  
  script: sudo apt-get install -y lftp; bash ftp_upload.sh
  skip_cleanup: true
