matrix:
  include:
    - os: linux-ppc64le
      dist: trusty
      env: OS=ubuntu_14.04
    - os: linux-ppc64le
      dist: xenial
      env: OS=ubuntu_16.04
language: java
sudo: required
jdk:
  - openjdk8

before_install:
  - python3 bazel_version.py
  - sudo apt-get update
  - sudo apt-get install -y build-essential python zip unzip 
  - sudo apt-get install -y lftp
script:
  - bash build.sh
